return {
  CmpItemAbbr = { fg = C.fg },
  CmpItemAbbrDeprecated = { fg = C.fg, style = "strikethrough" },
  CmpItemAbbrMatch = { fg = C.orange },
  CmpItemAbbrMatchFuzzy = { fg = U.shade(C.orange, -20) },
  CmpItemKind = { fg = C.red },
  CmpItemMenu = { fg = C.fg },

  CmpItemKindText = { fg = C.red },
  CmpItemKindMethod = { fg = C.syntax.func },
  CmpItemKindFunction = { fg = C.syntax.func },
  CmpItemKindConstructor = { fg = C.syntax.func },
  CmpItemKindField = { fg = C.syntax.field },
  CmpItemKindVariable = { fg = C.syntax.variable },
  CmpItemKindClass = { fg = C.syntax.type },
  CmpItemKindInterface = { fg = C.syntax.type },
  CmpItemKindModule = { fg = C.syntax.type },
  CmpItemKindProperty = { fg = C.syntax.field },
  CmpItemKindUnit = { fg = C.syntax.literal },
  CmpItemKindValue = { fg = C.syntax.literal },
  CmpItemKindEnum = { fg = C.syntax.type },
  CmpItemKindKeyword = { fg = C.syntax.red },
  CmpItemKindSnippet = { fg = C.red },
  CmpItemKindColor = { fg = C.syntax.literal },
  CmpItemKindFile = { fg = C.syntax.literal },
  CmpItemKindReference = { fg = C.syntax.variable },
  CmpItemKindFolder = { link = "Directory" },
  CmpItemKindEnumMember = { fg = C.syntax.type },
  CmpItemKindConstant = { fg = C.syntax.literal },
  CmpItemKindStruct = { fg = C.syntax.type },
  CmpItemKindEvent = { fg = C.syntax.type },
  CmpItemKindOperator = { fg = C.syntax.red },
  CmpItemKindTypeParameter = { fg = C.syntax.type },
}
