return {
  debugPC = { bg = C.bg_visual },

  DapUIVariable = { fg = C.magenta },
  DapUIScope = { fg = C.red },
  DapUIType = { fg = C.red },
  DapUIValue = { fg = C.orange },
  DapUIModifiedValue = { fg = C.orange, style = "bold" },
  DapUIDecoration = { fg = C.gray },
  DapUIThread = { fg = C.red },
  DapUIStoppedThread = { fg = C.red, style = "italic" },
  DapUIFrameName = { fg = C.magenta },
  DapUISource = { fg = C.red },
  DapUILineNumber = { link = "LineNr" },
  DapUIFloatBorder = { fg = C.border },
  DapUIWatchesEmpty = { fg = C.gray },
  DapUIWatchesValue = { fg = C.magenta },
  DapUIWatchesError = { fg = C.error },
  DapUIBreakpointsPath = { fg = C.red },
  DapUIBreakpointsInfo = { fg = C.red },
  DapUIBreakpointsCurrentLine = { fg = C.magenta },
  DapUIBreakpointsLine = { fg = C.gray },
  DapUIBreakpointsDisabledLine = { fg = C.gray },
}
