return {
  LazyButton = { bg = C.bg_visual },
  LazyButtonActive = { bg = C.orange },
  LazyComment = { link = "Comment" },
  LazyCommit = { fg = C.red },
  LazyCommitIssue = { fg = C.markup.link },
  LazyCommitScope = { fg = C.fg, style = "Italic" },
  LazyCommitType = { fg = C.magenta },
  LazyDir = { link = "Directory" },
  LazyH1 = { bg = C.orange },
  LazyH2 = { bg = C.bg_float },
  LazyNoCond = { link = "DiagnosticWarn" },
  LazyNormal = { bg = C.bg_float_bright },
  LazyProgressDone = { fg = C.pink },
  LazyProgressTodo = { fg = C.gray },
  LazyProp = { link = "Conceal" },
  LazyReasonCmd = { fg = C.red },
  LazyReasonEvent = { fg = C.red },
  LazyReasonFt = { fg = C.dark_pink },
  LazyReasonImport = { fg = C.magenta },
  LazyReasonKeys = { fg = C.red },
  LazyReasonPlugin = { fg = C.magenta },
  LazyReasonRuntime = { fg = C.red },
  LazyReasonSource = { fg = C.orange },
  LazyReasonStart = { fg = C.light_pink },
  LazySpecial = { fg = C.fg },
  LazyTaskError = { fg = C.error },
  LazyTaskOutput = { fg = C.fg },
  LazyUrl = { fg = C.markup.link },
  LazyValue = { fg = C.orange },
}
