return {
  NoiceCmdlineIcon = { fg = C.red },
  NoiceCmdlineIconSearch = { fg = C.red },
  NoiceCmdlinePopup = { fg = C.fg_gutter },
  NoiceCmdlinePopupBorder = { fg = C.dark_pink },
  NoiceCmdlinePopupBorderSearch = { fg = C.magenta },
  NoiceCmdlinePrompt = { link = "Question" },

  NoiceCompletionItemKindDefault = { fg = C.red },
  NoiceCompletionItemKindKeyword = { fg = C.red },
  NoiceCompletionItemKindVariable = { fg = C.syntax.variable },
  NoiceCompletionItemKindConstant = { fg = C.syntax.literal },
  NoiceCompletionItemKindReference = { fg = C.syntax.variable },
  NoiceCompletionItemKindValue = { fg = C.syntax.literal },
  NoiceCompletionItemKindFunction = { fg = C.syntax.func },
  NoiceCompletionItemKindMethod = { fg = C.syntax.func },
  NoiceCompletionItemKindConstructor = { fg = C.syntax.func },
  NoiceCompletionItemKindClass = { fg = C.syntax.type },
  NoiceCompletionItemKindInterface = { fg = C.syntax.type },
  NoiceCompletionItemKindStruct = { fg = C.syntax.type },
  NoiceCompletionItemKindEvent = { fg = C.syntax.type },
  NoiceCompletionItemKindEnum = { fg = C.syntax.type },
  NoiceCompletionItemKindUnit = { fg = C.syntax.type },
  NoiceCompletionItemKindModule = { fg = C.syntax.type },
  NoiceCompletionItemKindProperty = { fg = C.syntax.field },
  NoiceCompletionItemKindField = { fg = C.syntax.field },
  NoiceCompletionItemKindTypeParameter = { fg = C.syntax.type },
  NoiceCompletionItemKindEnumMember = { fg = C.syntax.field },
  NoiceCompletionItemKindOperator = { fg = C.red },
  NoiceCompletionItemKindSnippet = { fg = C.red },

  NoiceConfirm = { fg = C.red, style = "bold" },
  NoiceConfirmBorder = { fg = C.dark_pink },
}
